it('First Test', () => {
    assert.ok(textAgg(
        [{ "BundleKitDiscount": null, "BundleKitDiscountValue": null, "BundlePriceType": null, "CatalogID": 1, "CatalogItemType": 6, "DiscountAmount": 0, "FormData": [], "InStockHandlingDays": 1, "IsDeleted": false, "IsDeliverable": true, "IsFreeOffer": false, "IsFreeShipping": false, "IsGiftWrapping": false, "IsService": false, "OrderID": "b72f7a23-a9bb-4df0-b411-59b86987ad0d", "OrderItemID": 43862, "OutStockHandlingDays": 20, "ParentItemID": null, "Price": 84.9, "PriceListID": 1, "ProductID": 985222, "ProductIntegrationID": "6685", "Properties": [], "Qty": 1, "SKU": "1552", "SKUIntegrationID": "6685", "SellerSKU": null, "SerialKey": null, "SkuID": 985223, "SpecialType": 78, "Status": null, "Subtotal": 84.9, "TaxationAmount": 0, "Total": 84.9, "WareHouseID": 1, "Warehouses": [], "WebSiteID": 156 }]
        //[985222]
        , 'ProductID', 'ProductID = ', ' || ') === 'ProductID = 985222');
});

it('Second Test', () => {
    assert.ok(textAgg(
        [{ "BundleKitDiscount": null, "BundleKitDiscountValue": null, "BundlePriceType": null, "CatalogID": 1, "CatalogItemType": 6, "DiscountAmount": 0, "FormData": [], "InStockHandlingDays": 1, "IsDeleted": false, "IsDeliverable": true, "IsFreeOffer": false, "IsFreeShipping": false, "IsGiftWrapping": false, "IsService": false, "OrderID": "b72f7a23-a9bb-4df0-b411-59b86987ad0d", "OrderItemID": 43862, "OutStockHandlingDays": 20, "ParentItemID": null, "Price": 84.9, "PriceListID": 1, "ProductID": 985222, "ProductIntegrationID": "6685", "Properties": [], "Qty": 1, "SKU": "1552", "SKUIntegrationID": "6685", "SellerSKU": null, "SerialKey": null, "SkuID": 985223, "SpecialType": 78, "Status": null, "Subtotal": 84.9, "TaxationAmount": 0, "Total": 84.9, "WareHouseID": 1, "Warehouses": [], "WebSiteID": 156 }, { "BundleKitDiscount": null, "BundleKitDiscountValue": null, "BundlePriceType": null, "CatalogID": 1, "CatalogItemType": 6, "DiscountAmount": 0, "FormData": [], "InStockHandlingDays": 1, "IsDeleted": false, "IsDeliverable": true, "IsFreeOffer": false, "IsFreeShipping": false, "IsGiftWrapping": false, "IsService": false, "OrderID": "b72f7a23-a9bb-4df0-b411-59b86987ad0d", "OrderItemID": 43863, "OutStockHandlingDays": 20, "ParentItemID": null, "Price": 59.9, "PriceListID": 1, "ProductID": 985204, "ProductIntegrationID": "5768", "Properties": [], "Qty": 1, "SKU": "1533", "SKUIntegrationID": "5768", "SellerSKU": null, "SerialKey": null, "SkuID": 985205, "SpecialType": 78, "Status": null, "Subtotal": 59.9, "TaxationAmount": 0, "Total": 59.9, "WareHouseID": 1, "Warehouses": [], "WebSiteID": 156 }, { "BundleKitDiscount": null, "BundleKitDiscountValue": null, "BundlePriceType": null, "CatalogID": 1, "CatalogItemType": 6, "DiscountAmount": 0, "FormData": [], "InStockHandlingDays": 1, "IsDeleted": false, "IsDeliverable": true, "IsFreeOffer": false, "IsFreeShipping": false, "IsGiftWrapping": false, "IsService": false, "OrderID": "b72f7a23-a9bb-4df0-b411-59b86987ad0d", "OrderItemID": 43864, "OutStockHandlingDays": 20, "ParentItemID": null, "Price": 39.9, "PriceListID": 1, "ProductID": 985304, "ProductIntegrationID": "6429", "Properties": [], "Qty": 1, "SKU": "1632", "SKUIntegrationID": "6429", "SellerSKU": null, "SerialKey": null, "SkuID": 985305, "SpecialType": 78, "Status": null, "Subtotal": 39.9, "TaxationAmount": 0, "Total": 39.9, "WareHouseID": 1, "Warehouses": [], "WebSiteID": 156 }]
        //[985222, 985204, 985304]
        , 'ProductID', 'ProductID = ', ' || '
    ) === 'ProductID = 985222 || ProductID = 985204 || ProductID = 985304');
});

